image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: docker.zensoft.io/$CI_PROJECT_PATH


###########################
# Building
###########################
build-jar:
  stage: build
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - /backend/build/libs/*.jar
    expire_in: 1 day


###########################
# Packaging
###########################
package-docker:
  stage: package
  dependencies:
    - build-jar
  script:
    - if [[ ${CI_COMMIT_REF_NAME} == master ]]; then export IMAGE_TAG=latest; else export IMAGE_TAG=${CI_COMMIT_REF_NAME}; fi;
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.zensoft.io
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  only:
    - master
    - tags