version: '3'

services:

  db:
    image: postgres:10
    env_file: db.env
    restart: always

  kicker:
    depends_on:
      - db
    build: .
    image: zensoftio/kicker
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      SERVER_HOST: http://localhost:8080
      DOMAINS: ''
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data:/data