version: '3'

services:

  db:
    image: postgres:10
    env_file: db.env
    restart: always

  kicker:
    depends_on:
      - db
    build: .
    image: aliakseiyakovtsov/kicker
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      DOMAINS: ''
    ports:
      - 8585:8080
    restart: always
    volumes:
      - ./data:/data

volumes:
  pg_data: